-- Delete all data from CallBaodaozai table
DELETE FROM "CallBaodaozai";

-- AlterTable
ALTER TABLE "CallBaodaozai" ALTER COLUMN "home" SET NOT NULL,
ALTER COLUMN "home" SET DEFAULT '',
ALTER COLUMN "home" SET DATA TYPE TEXT,
ALTER COLUMN "topics" SET NOT NULL,
ALTER COLUMN "topics" SET DEFAULT '',
ALTER COLUMN "topics" SET DATA TYPE TEXT,
ALTER COLUMN "topic" SET NOT NULL,
ALTER COLUMN "topic" SET DEFAULT '',
ALTER COLUMN "topic" SET DATA TYPE TEXT,
ALTER COLUMN "news" SET NOT NULL,
ALTER COLUMN "news" SET DEFAULT '',
ALTER COLUMN "news" SET DATA TYPE TEXT,
ALTER COLUMN "comics" SET NOT NULL,
ALTER COLUMN "comics" SET DEFAULT '',
ALTER COLUMN "comics" SET DATA TYPE TEXT,
ALTER COLUMN "lessons" SET NOT NULL,
ALTER COLUMN "lessons" SET DEFAULT '',
ALTER COLUMN "lessons" SET DATA TYPE TEXT,
ALTER COLUMN "podcasts" SET NOT NULL,
ALTER COLUMN "podcasts" SET DEFAULT '',
ALTER COLUMN "podcasts" SET DATA TYPE TEXT,
ALTER COLUMN "aboutUs" SET NOT NULL,
ALTER COLUMN "aboutUs" SET DEFAULT '',
ALTER COLUMN "aboutUs" SET DATA TYPE TEXT;
